INSERT INTO public.company_issues (company_id, rank, name, summary, detail, score, rating, source_standard, source_reference, source_methodology, source_report_page) VALUES
-- Microsoft Corporation
('msft', 1, 'Supply chain Scope 3 emissions transparency', 'Limited third-party verification of purchased goods and services emissions.', 'Microsoft discloses Scope 3 estimates across its value chain, but the breakdown relies heavily on spend-based emission factors rather than supplier-reported data. Independent assurance covers only a subset, leaving the headline reduction claims difficult to fully verify.', 45, 'Average', 'IFRS S2 / GHG Protocol', 'Scope 3 Category 1-15 disclosures', 'Spend-based emission factors compared against supplier-reported data where available', '2024 Environmental Sustainability Report pp. 34-37'),
('msft', 2, 'Water stress in data centre regions', 'Rapid data centre expansion is outpacing detailed water-risk disclosure.', 'New AI-training and cloud capacity is concentrated in regions facing water stress. While the company reports total freshwater withdrawals, site-level water stress exposure and local mitigation plans are not consistently disclosed.', 52, 'Average', 'GRI 303 / IFRS S2', 'Water and security data', 'Withdrawal totals mapped to WRI Aqueduct water stress scores by facility location', '2024 Water Stewardship Update pp. 8-11'),
('msft', 3, 'AI ethics and governance disclosures', 'Board-level oversight of responsible AI is described but not evidenced in detail.', 'The company publishes high-level AI principles and a responsible AI office, yet the linkage between board risk oversight and specific product-level decisions is not documented in filed disclosures.', 68, 'Strong', 'GRI 2-9 / GRI 2-12', 'Governance and responsible AI statements', 'Review of governance disclosures against product incident reporting', '2024 Responsible AI Transparency Report pp. 5-9'),
-- Apple Inc.
('aapl', 1, 'Manufacturing supply chain carbon neutrality claims', 'Supplier clean energy claims are central to Apples net-zero positioning but verification is partial.', 'Apple states that manufacturing partners have committed to 100% renewable energy. However, the evidence supporting those commitments, retirement of renewable energy credits, and supplier-level progress are not fully detailed in public filings.', 48, 'Average', 'IFRS S2 / GHG Protocol', 'Supplier clean energy programme disclosures', 'Supplier survey data cross-checked with renewable energy certificate claims', '2024 Environmental Progress Report pp. 28-31'),
('aapl', 2, 'Rare earth and conflict mineral sourcing', 'Due diligence on 3TG and cobalt is reported, but rare earth supply chain coverage is limited.', 'Conflict minerals filings disclose smelter and refiner audits for tin, tantalum, tungsten and gold. The report does not extend the same depth of disclosure to rare earth elements used in magnets and batteries.', 55, 'Average', 'GRI 408 / GRI 409', 'Conflict minerals report and supplier list', 'Smelter and refiner audit data matched against product bill of materials', '2024 Conflict Minerals Report pp. 12-15'),
('aapl', 3, 'Product repairability and circular economy', 'Repair and recycling programmes exist, but design-for-repair metrics remain thin.', 'The company operates a trade-in and authorised repair network. Quantified design-for-longevity metrics, such as modular component scores or mean time to repair, are not disclosed.', 62, 'Strong', 'GRI 306 / EU CSRD', 'Circular economy and recycling disclosures', 'Review of repair programme disclosures and recycling material flow data', '2024 Environmental Progress Report pp. 42-45'),
-- BHP Group Limited
('bhp', 1, 'Scope 3 downstream emissions from steelmaking', 'The largest emissions exposure sits outside operational control and remains weakly evidenced.', 'BHPs Scope 3 emissions are dominated by customers processing iron ore into steel. While the company discloses customer-related estimates, the linkage to specific decarbonisation pathways for steelmaking is not supported by verifiable customer commitments.', 38, 'Laggard', 'IFRS S2 / GHG Protocol', 'Scope 3 Category 10 downstream processing', 'Emission estimates compared with steel sector decarbonisation scenario benchmarks', '2024 Climate Transition Action Plan pp. 18-22'),
('bhp', 2, 'Tailings storage facility risk disclosure', 'Tailings dam management is disclosed at a high level without facility-specific risk data.', 'BHP reports governance over tailings facilities and independent reviews. Facility-by-failure consequence classification and emergency preparedness details are not publicly disclosed for all assets.', 42, 'Average', 'GRI 2-27 / ICMM', 'Tailings management disclosures', 'Review of Global Industry Standard on Tailings Management conformance claims', '2024 Annual Report pp. 56-59'),
('bhp', 3, 'Biodiversity and rehabilitation commitments', 'Net-positive impact targets are stated, but baseline biodiversity metrics are not fully evidenced.', 'The company has committed to nature-positive outcomes by 2030. Baseline ecosystem condition data and project-level biodiversity offset ratios are not consistently disclosed.', 58, 'Average', 'GRI 304 / TNFD', 'Biodiversity and land management disclosures', 'Baseline condition assessments compared against rehabilitation targets', '2024 Nature Positive Report pp. 10-14'),
-- Nestle S.A.
('nesn', 1, 'Deforestation-free supply chain verification', 'Palm oil, soy and pulp claims are improving, but full traceability to farm level is incomplete.', 'Nestle reports high percentages of deforestation-free verified supplies for key commodities. Independent monitoring shows traceability gaps for indirect suppliers and smallholder sourcing, which are not fully reflected in headline claims.', 50, 'Average', 'GRI 308 / CDP Forests', 'Deforestation-free supply chain reporting', 'Supplier certification data matched against satellite deforestation alerts', '2024 Creating Shared Value Report pp. 32-36'),
('nesn', 2, 'Water stewardship in high-risk watersheds', 'Water replenishment claims are supported, but context-based water targets are limited.', 'The company discloses total water withdrawals and replenishment projects. Context-based targets that reflect local water availability and community water needs are not consistently applied across high-risk sites.', 61, 'Strong', 'GRI 303 / AWS', 'Water stewardship reporting', 'Withdrawal data compared to basin water stress and local community usage', '2024 Water Report pp. 16-19'),
('nesn', 3, 'Child labour and human rights due diligence', 'Human rights saliency mapping is disclosed, but remediation outcomes are not detailed.', 'Nestle publishes a human rights saliency assessment and supplier code. The number of identified child labour incidents, remediation actions taken, and outcomes for affected workers are not fully disclosed.', 44, 'Average', 'GRI 407 / UNGP', 'Human rights and responsible sourcing reports', 'Supplier audit results matched against disclosed remediation procedures', '2024 Human Rights Report pp. 24-28'),
-- Shell plc
('shel', 1, 'Net-zero 2050 pathway credibility', 'The energy transition plan relies on continued fossil fuel investment and carbon offsets.', 'Shells net-zero strategy includes emissions intensity reduction targets, but the plan still anticipates significant oil and gas production through 2050. Dependence on carbon capture and nature-based offsets is not fully backed by executed project commitments.', 35, 'Laggard', 'IFRS S2 / TCFD', 'Energy transition strategy and capital allocation', 'Production and capex plans compared against net-zero scenario benchmarks', '2024 Energy Transition Progress Report pp. 8-13'),
('shel', 2, 'Methane emissions measurement and reporting', 'Methane intensity figures are disclosed, but measurement methodology varies across assets.', 'Shell reports methane intensity and leak detection programmes. The split between measured emissions and modelled estimates, and the coverage of non-operated assets, is not consistently disclosed.', 47, 'Average', 'GRI 305 / OGMP 2.0', 'Methane emissions reporting', 'Reported intensity compared against satellite measurement where available', '2024 Sustainability Report pp. 44-47'),
('shel', 3, 'Just transition and workforce disclosures', 'Workforce transition plans are referenced but reskilling metrics are limited.', 'The company acknowledges the need to support workers through the transition. Quantified reskilling investment, job displacement forecasts, and community transition programmes are not detailed in public disclosures.', 51, 'Average', 'GRI 404 / Just Transition', 'Workforce and social disclosures', 'Employment and training data compared against stated transition plans', '2024 People and Society Report pp. 20-24');