CREATE TYPE public.materiality_component AS ENUM ('Revenue','Expenses','Assets & Liabilities','Cost of capital');
CREATE TYPE public.valuation_direction AS ENUM ('Headwind','Neutral','Tailwind');

CREATE TABLE public.financial_materiality (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  company_id text NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE,
  component public.materiality_component NOT NULL,
  direction public.valuation_direction NOT NULL,
  summary text NOT NULL,
  detail text NOT NULL,
  financial_reference text NOT NULL,
  sort_order integer NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (company_id, component)
);

GRANT SELECT ON public.financial_materiality TO anon;
GRANT SELECT ON public.financial_materiality TO authenticated;
GRANT ALL ON public.financial_materiality TO service_role;

ALTER TABLE public.financial_materiality ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Financial materiality is publicly readable"
ON public.financial_materiality FOR SELECT USING (true);

INSERT INTO public.financial_materiality (company_id, component, direction, summary, detail, financial_reference, sort_order) VALUES
('msft','Revenue','Tailwind','Carbon-aware cloud demand supports Azure pricing and enterprise win rates.','Microsoft Cloud revenue of $137.4bn in FY24 (+23%) is increasingly tied to customers with their own disclosure obligations; sustainability tooling embedded in Azure and Fabric raises switching costs and supports premium pricing on committed capacity. Volume risk is limited: no material demand exposure to transition policy. The upside is pricing and attach rate rather than new volume.','FY24 Form 10-K, MD&A — segment revenue; 2024 Environmental Sustainability Report',1),
('msft','Expenses','Headwind','Scope 3 and datacentre energy costs rise faster than revenue as AI capacity scales.','Total emissions are 29.1% above the 2020 baseline, driven almost entirely by Scope 3 construction and hardware. Microsoft is absorbing this through long-dated PPAs and carbon removal contracts, which convert a future carbon liability into a present operating cost. Expect continued pressure on cloud gross margin from energy and internal carbon fee charges rather than a step-change in COGS.','FY24 Form 10-K — cost of revenue; 2024 Environmental Sustainability Report',2),
('msft','Assets & Liabilities','Headwind','Record capex concentrates capital in energy- and water-constrained datacentre regions.','FY24 capital expenditure including finance leases reached $44.5bn, over half of it long-lived datacentre assets with 15-year useful lives. Physical risk is grid and water availability rather than asset damage; siting constraints, not remediation, is the stranding vector. Water-positive commitments add modest capital cost per site.','FY24 Form 10-K — PP&E and capital expenditures',3),
('msft','Cost of capital','Tailwind','AAA balance sheet plus credible transition plan sustains a modest green premium.','Microsoft raises debt at the tightest end of the corporate curve and its sustainability disclosure quality removes the ESG-related risk premium some peers carry. No evidence of hurdle-rate uplift for energy-intensive projects being applied inconsistently.','FY24 Form 10-K — debt footnote; credit rating disclosures',4),

('aapl','Revenue','Neutral','Sustainability supports brand pricing but is not a demand driver.','Net sales of $391.0bn in FY24 show no measurable sustainability-linked volume effect. Trade-in and recycled-content programmes reinforce premium positioning and support installed-base retention, but revenue sensitivity to transition policy remains immaterial in disclosed segments.','FY24 Form 10-K — net sales by segment; FY24 Environmental Progress Report',1),
('aapl','Expenses','Headwind','Recycled materials and clean-energy mandates raise supplier input costs.','Apple requires suppliers to move to renewable electricity for Apple production, with the cost embedded in component pricing rather than Apple''s own operating expense. Recycled cobalt, rare earth and aluminium content carries a premium over primary material. Gross margin of 46.2% has absorbed this to date, but the cost sits in COGS and is not separately hedged.','FY24 Form 10-K — cost of sales and gross margin; Supplier Clean Energy Program',2),
('aapl','Assets & Liabilities','Neutral','Asset-light model limits physical and stranded-asset exposure.','Owned PP&E of $45.7bn is small relative to revenue, and manufacturing risk is carried by suppliers. Physical climate risk concentrates in contract manufacturing geographies and appears as supply continuity risk, not impairment. No material remediation provisions disclosed.','FY24 Form 10-K — PP&E; commitments and contingencies',3),
('aapl','Cost of capital','Tailwind','Green bond issuance broadens the investor base at no yield penalty.','Apple''s green bond programme funds low-carbon manufacturing and clean energy, and has priced in line with conventional issuance. Combined with a large buyback programme, the practical effect on WACC is marginal but directionally favourable.','FY24 Form 10-K — term debt footnote; Green Bond Impact Report',4),

('bhp','Revenue','Headwind','Steelmaking coal and iron ore volumes are exposed to steel decarbonisation.','FY24 revenue of $55.7bn remains concentrated in iron ore and coking coal, both tied to blast-furnace steelmaking. Copper revenue growth partly offsets this, and copper is the clearest transition-demand beneficiary in the portfolio. Price, not volume, is the near-term sensitivity: realised coal pricing is the swing factor.','FY24 Annual Report — revenue by commodity; Climate Transition Action Plan',1),
('bhp','Expenses','Headwind','Diesel displacement and carbon pricing lift unit cash costs.','Operational decarbonisation of haul fleets and rail carries higher near-term unit cost than diesel, and Australian Safeguard Mechanism baselines bring a direct carbon cost into COGS. BHP guides to unit cost discipline, but the abatement capital and energy contracting both land in the cost base before volume benefits appear.','FY24 Annual Report — unit costs by asset; Safeguard Mechanism disclosures',2),
('bhp','Assets & Liabilities','Headwind','Samarco and closure provisions dominate the liability picture.','Samarco dam failure provisions and long-dated mine closure and rehabilitation liabilities are the largest sustainability-linked items on the balance sheet, with closure estimates sensitive to discount rate and scope assumptions. Physical risk — water stress in Chile, cyclone exposure in the Pilbara — affects production reliability and sustaining capex.','FY24 Annual Report — provisions for closure and rehabilitation; Samarco contingent liabilities',3),
('bhp','Cost of capital','Headwind','Coal exposure sustains an ESG risk premium on equity.','Some mandates exclude or underweight thermal and steelmaking coal producers, narrowing the buyer base and supporting a higher required return. BHP applies internal carbon pricing to investment decisions, which raises effective hurdle rates on carbon-intensive growth options while improving copper project relative attractiveness.','FY24 Annual Report — capital allocation framework and internal carbon price',4),

('nesn','Revenue','Headwind','Reformulation and pack regulation weigh on volume and mix.','FY24 sales of CHF 91.4bn with real internal growth near flat: pricing carried the top line while volumes lagged. Nutrition and health scrutiny, plus packaging regulation in the EU, constrain portfolio pricing power in confectionery and beverages, while plant-based and premium coffee lines provide partial mix offset.','FY24 Annual Report — RIG and pricing by zone; Creating Shared Value Report',1),
('nesn','Expenses','Headwind','Regenerative-agriculture sourcing and deforestation compliance raise COGS.','Cocoa and coffee input inflation is compounded by premiums paid under the Nescafé and Cocoa Plans and by EU Deforestation Regulation traceability costs. These sit directly in cost of goods sold and in supply chain overhead. Packaging redesign for recyclability adds conversion cost ahead of any material saving.','FY24 Annual Report — cost of goods sold and commodity input commentary',2),
('nesn','Assets & Liabilities','Headwind','Water-stressed factory sites and agricultural physical risk drive capex.','A meaningful share of factories operate in water-stressed catchments, requiring efficiency and reuse capex with limited direct payback. Upstream physical risk in cocoa and coffee growing regions is the more material valuation issue: yield volatility feeds input cost and working capital rather than impairment.','FY24 Annual Report — PP&E and capital expenditure; water stewardship disclosures',3),
('nesn','Cost of capital','Neutral','Sustainability-linked financing is in place but pricing benefit is small.','Nestlé''s credit quality and sustainability-linked facility margins produce only a few basis points of benefit. No evidence of an ESG-driven premium on equity; the discount-rate question is dominated by volume recovery, not disclosure quality.','FY24 Annual Report — financing costs and debt footnote',4),

('shel','Revenue','Headwind','Hydrocarbon volume trajectory is the central valuation question.','FY24 revenue of $284.3bn remains overwhelmingly hydrocarbon-derived. Shell retreated from earlier absolute oil production decline commitments and weakened its 2030 intensity target, which supports near-term cash generation but increases exposure to demand destruction later in the decade. LNG is the resilient volume story; power and low-carbon revenue remains immaterial to group scale.','FY24 Annual Report and Form 20-F — revenue by segment; Energy Transition Strategy 2024',1),
('shel','Expenses','Headwind','EU ETS and methane abatement costs are now recurring, not one-off.','Carbon compliance costs across European refining and chemicals are a structural operating expense, and methane detection and repair programmes add sustaining cost across upstream assets. Shell''s cost discipline programme partly masks this by netting abatement spend against wider opex reduction.','FY24 Annual Report — operating expenses; emissions and carbon cost disclosures',2),
('shel','Assets & Liabilities','Headwind','Impairments and decommissioning provisions show the stranding channel directly.','Low-carbon and refining impairments in FY24, alongside multi-billion decommissioning and asset restoration obligations, are the clearest evidence of sustainability translating into balance-sheet value destruction. Reserve-life assumptions and price-deck choices remain the dominant sensitivity for upstream carrying value; Niger Delta remediation exposure is unresolved.','FY24 Annual Report — impairments, decommissioning and restoration provisions',3),
('shel','Cost of capital','Headwind','Divestment pressure and litigation risk keep the required return elevated.','Shell trades at a persistent discount to US majors, and exclusion policies plus climate litigation exposure sustain a higher equity risk premium. Internally, low-carbon projects are held to the same 10%+ hurdle rate as hydrocarbon projects, which limits transition capital deployment and reinforces the market''s discount.','FY24 Annual Report — capital discipline and hurdle rate commentary; legal proceedings',4);