ALTER TABLE public.assessment_criteria
  ADD COLUMN IF NOT EXISTS methodology text,
  ADD COLUMN IF NOT EXISTS source_reference text;

-- Microsoft
UPDATE public.assessment_criteria SET methodology = 'Targets tested for absolute reduction scope, base-year integrity and coverage of Scope 1-3. Carbon negative 2030 commitment covers the full value chain and is backed by an approved science-based target, placing stated ambition above the sector distribution.', source_reference = 'IFRS S2 paras 33-37 (climate targets); Microsoft Environmental Sustainability Report, targets section' WHERE company_id = 'msft' AND name = 'Ambition';
UPDATE public.assessment_criteria SET methodology = 'Stated commitments reconciled against reported progress and third-party assurance. Emissions and energy data carry external limited assurance and multi-year trends move in the direction the targets require, with no restatements that reset the baseline.', source_reference = 'IFRS S1 paras 37-41 (faithful representation); independent assurance statement, Microsoft annual sustainability data' WHERE company_id = 'msft' AND name = 'Credibility';
UPDATE public.assessment_criteria SET methodology = 'Disclosure completeness scored against IFRS S1/S2 and GRI index coverage, including Scope 3 category-level detail, methodology notes and data tables at reporting-unit level. Gaps are counted where a required item is referenced but not quantified.', source_reference = 'IFRS S1 general requirements; GRI 2 and GRI 305 index; Microsoft data fact sheet' WHERE company_id = 'msft' AND name = 'Transparency';
UPDATE public.assessment_criteria SET methodology = 'Governance tested for named board oversight, committee mandate and whether sustainability outcomes affect executive pay. Climate and inclusion measures appear in the executive incentive scorecard, and oversight sits with an identified board committee.', source_reference = 'IFRS S2 paras 6-7 (governance); proxy statement, executive compensation discussion' WHERE company_id = 'msft' AND name = 'Accountability';
UPDATE public.assessment_criteria SET methodology = 'Assessed whether outcomes would have occurred anyway. Direct procurement of durable carbon removal and grid-additive power purchase agreements create new capacity rather than transferring existing attributes, which is a higher bar than avoidance offsets.', source_reference = 'GRI 305-5 (reductions); Microsoft carbon removal portfolio disclosure' WHERE company_id = 'msft' AND name = 'Additionality';

-- Apple
UPDATE public.assessment_criteria SET methodology = 'Target architecture reviewed for coverage and date. Carbon neutrality already achieved for operations, with a 2030 commitment extending across the product value chain, so ambition is tested against Scope 3 reach rather than operational footprint alone.', source_reference = 'IFRS S2 paras 33-37 (climate targets); Apple Environmental Progress Report, 2030 roadmap' WHERE company_id = 'aapl' AND name = 'Ambition';
UPDATE public.assessment_criteria SET methodology = 'Progress reconciled year on year against the stated pathway. Operational claims are supported by verified renewable energy data; supplier decarbonisation is disclosed as enrolled capacity rather than delivered abatement, so part of the pathway remains forward-looking.', source_reference = 'IFRS S1 paras 37-41; Apple Supplier Clean Energy Program annual update' WHERE company_id = 'aapl' AND name = 'Credibility';
UPDATE public.assessment_criteria SET methodology = 'Reporting tested for granularity and framework alignment. Supplier audit findings, remediation rates and product life-cycle assessments are published at a level that allows independent recalculation across several frameworks.', source_reference = 'GRI 2-6 and GRI 414; Apple Supplier Responsibility Progress Report' WHERE company_id = 'aapl' AND name = 'Transparency';
UPDATE public.assessment_criteria SET methodology = 'Oversight and consequence tested separately. Board committee responsibility for environmental matters is explicit, but the link between sustainability outcomes and executive remuneration is described qualitatively rather than as a weighted metric.', source_reference = 'IFRS S2 paras 6-7 (governance); Apple proxy statement, committee charters' WHERE company_id = 'aapl' AND name = 'Accountability';
UPDATE public.assessment_criteria SET methodology = 'Tested whether reported reductions are real-world and attributable. The supplier clean energy program brings new renewable capacity online in supplier grids, producing abatement outside the reporting boundary that would not otherwise occur.', source_reference = 'GRI 305-5; Apple Supplier Clean Energy Program disclosure' WHERE company_id = 'aapl' AND name = 'Additionality';

-- BHP
UPDATE public.assessment_criteria SET methodology = 'Target ambition benchmarked against sector transition pathways. A 30% operational reduction by 2030 sits below leading diversified miners, and the Scope 3 position is expressed as an intent with customer engagement rather than a quantified pathway.', source_reference = 'IFRS S2 paras 33-37; BHP Climate Transition Action Plan' WHERE company_id = 'bhp' AND name = 'Ambition';
UPDATE public.assessment_criteria SET methodology = 'Delivery record compared with stated targets. Operational emissions are tracking to plan with assured data, while the Scope 3 element lacks the interim milestones and abatement levers needed to test progress in any given year.', source_reference = 'IFRS S1 paras 37-41; BHP Annual Report, assured emissions data' WHERE company_id = 'bhp' AND name = 'Credibility';
UPDATE public.assessment_criteria SET methodology = 'Disclosure tested for scenario analysis, asset-level detail and methodology notes. Multiple climate scenarios with financial implications are published and cross-referenced to the financial statements, exceeding baseline expectations.', source_reference = 'IFRS S2 paras 22-23 (climate resilience); BHP Climate Transition Action Plan, scenario section' WHERE company_id = 'bhp' AND name = 'Transparency';
UPDATE public.assessment_criteria SET methodology = 'Accountability tested through shareholder mechanisms and board structure. An advisory Say-on-Climate vote and an active board sustainability committee create a recurring consequence pathway, though pay linkage weighting remains modest.', source_reference = 'IFRS S2 paras 6-7; BHP Notice of Meeting and Remuneration Report' WHERE company_id = 'bhp' AND name = 'Accountability';
UPDATE public.assessment_criteria SET methodology = 'Assessed whether spend changes outcomes. Community and social investment is substantiated, and decarbonisation capital expenditure is rising, but the deployed share remains small relative to the abatement task disclosed.', source_reference = 'GRI 203-1 and GRI 305-5; BHP Annual Report, capital expenditure notes' WHERE company_id = 'bhp' AND name = 'Additionality';

-- Nestle
UPDATE public.assessment_criteria SET methodology = 'Targets tested for interim milestones. Net zero by 2050 is supported by quantified 2030 interim targets covering operations and the agricultural supply chain, so ambition rests on near-term checkpoints rather than a distant endpoint alone.', source_reference = 'IFRS S2 paras 33-37; Nestle Net Zero Roadmap' WHERE company_id = 'nesn' AND name = 'Ambition';
UPDATE public.assessment_criteria SET methodology = 'Reported progress compared against each commitment separately. Nutrition and sourcing goals track to plan, while packaging recyclability and virgin plastic reduction have slipped against original timelines, lowering confidence in the aggregate pathway.', source_reference = 'IFRS S1 paras 37-41; Nestle Creating Shared Value and Sustainability Report' WHERE company_id = 'nesn' AND name = 'Credibility';
UPDATE public.assessment_criteria SET methodology = 'Disclosure completeness assessed across environmental and product dimensions, including a full GRI index, IFRS-aligned climate content and product-level nutrition data that allows independent verification of claims.', source_reference = 'GRI 2 and GRI 416 index; Nestle sustainability data tables' WHERE company_id = 'nesn' AND name = 'Transparency';
UPDATE public.assessment_criteria SET methodology = 'Governance tested for consequence and stakeholder mechanisms. Sustainability measures form part of leadership incentives and a standing stakeholder engagement process feeds the materiality assessment, though metric weightings are partially disclosed.', source_reference = 'IFRS S2 paras 6-7; Nestle Annual Review, remuneration section' WHERE company_id = 'nesn' AND name = 'Accountability';
UPDATE public.assessment_criteria SET methodology = 'Tested for outcomes beyond business-as-usual. Regenerative agriculture programmes and affordable nutrition initiatives change practices at farm and consumer level, producing effects attributable to the company rather than market trend.', source_reference = 'GRI 203-2 and GRI 308-2; Nestle regenerative agriculture programme reporting' WHERE company_id = 'nesn' AND name = 'Additionality';

-- Shell
UPDATE public.assessment_criteria SET methodology = 'Ambition assessed against the direction of successive target revisions. Intensity targets have been weakened relative to earlier commitments while upstream investment continues, so stated ambition does not align with a credible transition pathway.', source_reference = 'IFRS S2 paras 33-37; Shell Energy Transition Strategy, revised targets' WHERE company_id = 'shel' AND name = 'Ambition';
UPDATE public.assessment_criteria SET methodology = 'Credibility scored on the stability of commitments over time. Repeated restatements and withdrawn interim goals mean current targets cannot be tested against a consistent baseline, which materially reduces confidence in stated plans.', source_reference = 'IFRS S1 paras 37-41 (comparability); Shell Annual Report, target history' WHERE company_id = 'shel' AND name = 'Credibility';
UPDATE public.assessment_criteria SET methodology = 'Disclosure structure reviewed for framework alignment and methodology detail. Climate reporting follows recognised structure, but Scope 3 boundary and intensity methodology contain gaps that prevent independent recalculation.', source_reference = 'IFRS S2 paras 29-31 (Scope 3 measurement); Shell Sustainability Report, basis of reporting' WHERE company_id = 'shel' AND name = 'Transparency';
UPDATE public.assessment_criteria SET methodology = 'Accountability tested through shareholder votes and pay design. An advisory climate vote has been put to shareholders, but transition delivery carries limited weight in executive remuneration, weakening the consequence pathway.', source_reference = 'IFRS S2 paras 6-7; Shell Notice of Meeting and Directors Remuneration Report' WHERE company_id = 'shel' AND name = 'Accountability';
UPDATE public.assessment_criteria SET methodology = 'Assessed whether low-carbon spend creates additional outcomes. Reported low-carbon capital expenditure includes gas infrastructure classified within the transition category, so the genuinely additional share is materially smaller than headline figures suggest.', source_reference = 'GRI 305-5; Shell Annual Report, capital expenditure by segment' WHERE company_id = 'shel' AND name = 'Additionality';